services:
  # WordPress application
  - type: web
    name: stretch-creative
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: stretch-db
          property: host
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: stretch-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: stretch-db
          property: password
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: stretch-db
          property: database
      - key: WORDPRESS_DEBUG
        value: "0"
    disk:
      name: wp-uploads
      mountPath: /var/www/html/wp-content/uploads
      sizeGB: 1

databases:
  - name: stretch-db
    databaseName: stretch_wp
    user: stretch
    plan: free
