services:
  - type: web
    name: stretch-bespoke-content
    runtime: static
    buildCommand: ""
    staticPublishPath: ./public
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
